# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pb_folder.setObjectName("pb_folder")
        self.horizontalLayout_2.addWidget(self.pb_folder)
        self.pb_save = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_2.addWidget(self.pb_save)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lw_pict = QtWidgets.QListWidget(self.centralwidget)
        self.lw_pict.setObjectName("lw_pict")
        self.verticalLayout.addWidget(self.lw_pict)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_picture = QtWidgets.QLabel(self.centralwidget)
        self.l_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.l_picture.setObjectName("l_picture")
        self.verticalLayout_2.addWidget(self.l_picture)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_left = QtWidgets.QPushButton(self.centralwidget)
        self.pb_left.setObjectName("pb_left")
        self.horizontalLayout.addWidget(self.pb_left)
        self.pb_right = QtWidgets.QPushButton(self.centralwidget)
        self.pb_right.setObjectName("pb_right")
        self.horizontalLayout.addWidget(self.pb_right)
        self.pb_mirror = QtWidgets.QPushButton(self.centralwidget)
        self.pb_mirror.setObjectName("pb_mirror")
        self.horizontalLayout.addWidget(self.pb_mirror)
        self.pb_sharpen = QtWidgets.QPushButton(self.centralwidget)
        self.pb_sharpen.setObjectName("pb_sharpen")
        self.horizontalLayout.addWidget(self.pb_sharpen)
        self.pb_BlackWhite = QtWidgets.QPushButton(self.centralwidget)
        self.pb_BlackWhite.setObjectName("pb_BlackWhite")
        self.horizontalLayout.addWidget(self.pb_BlackWhite)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_folder.setText(_translate("MainWindow", "Папка"))
        self.pb_save.setText(_translate("MainWindow", "Зберегти"))
        self.l_picture.setText(_translate("MainWindow", "Картинка"))
        self.pb_left.setText(_translate("MainWindow", "Вліво"))
        self.pb_right.setText(_translate("MainWindow", "Вправо"))
        self.pb_mirror.setText(_translate("MainWindow", "Дзеркально"))
        self.pb_sharpen.setText(_translate("MainWindow", "Різкість"))
        self.pb_BlackWhite.setText(_translate("MainWindow", "Ч/Б"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
